# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: d1ver
    volumes: 
      - ./db/initsql:/docker-entrypoint-initdb.d/:ro
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  dive-frontend:
    image: petwa/diveapi:v1.1.4
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./dive-frontend/logs:/app/logs
      - ./dive-frontend/config:/app/config
  
volumes:
    data-volume:
    db-volume:

